/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varun' at '22/11/18 12:16 PM' with Gradle 3.0
 *
 * @author Varun, @date 22/11/18 12:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
